-- RESET:
DROP DATABASE `coursecritics`;

-- MySQL Script generated by MySQL Workbench
-- Tue Feb 13 11:58:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema coursecritics
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coursecritics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coursecritics` DEFAULT CHARACTER SET utf8 ;
USE `coursecritics` ;

-- -----------------------------------------------------
-- Table `coursecritics`.`school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursecritics`.`school` (
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursecritics`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursecritics`.`course` (
  `name` VARCHAR(255) NOT NULL,
  `school_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`),
  INDEX `fk_course_school_idx` (`school_name` ASC),
  CONSTRAINT `fk_course_school`
    FOREIGN KEY (`school_name`)
    REFERENCES `coursecritics`.`school` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursecritics`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursecritics`.`user` (
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursecritics`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursecritics`.`review` (
  `course_name` VARCHAR(255) NOT NULL,
  `user_username` VARCHAR(255) NOT NULL,
  `quality` INT NULL,
  `relevance` INT NULL,
  `difficulty` INT NULL,
  `teaching` INT NULL,
  `comment` VARCHAR(500) NULL,
  INDEX `fk_review_user1_idx` (`user_username` ASC),
  PRIMARY KEY (`user_username`),
  INDEX `fk_review_course1_idx` (`course_name` ASC),
  CONSTRAINT `fk_review_user1`
    FOREIGN KEY (`user_username`)
    REFERENCES `coursecritics`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_course1`
    FOREIGN KEY (`course_name`)
    REFERENCES `coursecritics`.`course` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
